# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# TODO: REMOVE FROM dotfiles, append source line below:
source ~/.my_zshrc

# START oh-my-zsh
source $ZSH/oh-my-zsh.sh 
# Double sourcing is fixing this but shouldn't do this
source ~/.my_zshrc
export LANG=en_US.UTF-8 
export PATH="$PATH:$HOME/.bin"

export PATH="$PATH:$HOME/scripts" 
export PATH="$PATH:$HOME/.local/bin"

# no clue what this is
export TERM_ITALICS=true
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Created by `pipx` on 2023-10-05 20:57:33
export PATH="$PATH:/home/dwm/.local/bin"

export PATH="$PATH:/home/dwm/.local/share/JetBrains/Toolbox/scripts"
export PATH="$PATH:/home/dwm/bin"
export PICO_SDK_PATH="/home/dwm/pico/pico-sdk"

